name: Pre-commit

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: UV Sync (timeboxed)
        run: |
          source ./bin/activate
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
        timeout-minutes: 5
      - uses: pre-commit/action@v3.0.1
      - run: uv cache prune --ci
